import fs from "node:fs";
import path from "node:path";
import type { Law } from "../laws.js";
import {
  type CompileContext,
  type CompiledArtifact,
  type Dialect,
  commonPrefix,
  delimit,
} from "./types.js";

const NESTED_THRESHOLD = 3;

const LAWS_BLOCK_RE = /<!-- speclaw:laws:start -->[\s\S]*?<!-- speclaw:laws:end -->/;

/**
 * The agent workflow speclaw relies on (Compass first, Cortex with the Stop
 * hook), emitted in the generated block only when the hand-written part of
 * AGENTS.md lacks it.
 *
 * @remarks
 * `update` never edits the personalized AGENTS.md, so a project scaffolded
 * before Cortex (or one with a hand-written AGENTS.md) never learned to record
 * its work in the lawbook. The generated block is rewritten on every update,
 * so it carries the rule there; a file that already states it pays no tokens.
 *
 * @param projectPath - Project root holding AGENTS.md.
 * @returns The section's lines, or none when AGENTS.md already covers it.
 */
export function workflowSection(projectPath: string): string[] {
  let own = "";
  try {
    own = fs.readFileSync(path.join(projectPath, "AGENTS.md"), "utf8").replace(LAWS_BLOCK_RE, "");
  } catch {
    // No AGENTS.md yet: the section goes in.
  }
  if (/\bCortex\b/.test(own) && /\bcompass_explore\b/.test(own)) return [];
  return [
    "## speclaw workflow (generated)",
    "",
    "- **Compass first.** For any code question call `compass_find` / `compass_explore`",
    "  before grep or reading files; run `compass_index` first if the graph is missing.",
    "- **Cortex for every change.** Branch `<type>/<slug>`, locate with Compass, implement",
    "  the change and its test, run the tests, then stop. In Claude Code the `Stop` hook",
    "  (`speclaw ship-on-stop`) records the change in `lawbook/` and runs the gates; agents",
    '  without hooks run `speclaw ship <change> --summary "<what and why>"` once, last.',
    "  Work that needs a spec goes through the `cortex` skill.",
    "",
  ];
}

function degradeSection(title: string, laws: Law[]): string {
  const lines = [`## ${title}`, ""];
  for (const law of laws) {
    const globHint =
      law.scope.length > 0 ? `In files that match \`${law.scope.join("`, `")}\`, ` : "";
    lines.push(`### ${law.title} (\`${law.id}\`)`);
    lines.push("");
    lines.push(`${globHint}${law.prose}`);
    lines.push("");
  }
  return lines.join("\n");
}

/**
 * AGENTS.md dialect: move scope into prose; optional nested AGENTS.md files.
 * Emits patch-delimited content for the root file.
 */
export const agentsmdDialect: Dialect = {
  id: "agentsmd",
  compile(laws: Law[], ctx: CompileContext): CompiledArtifact[] {
    const active = laws.filter((l) => (l.status ?? "active") !== "draft");
    const global = active.filter((l) => l.scope.length === 0);
    const scoped = active.filter((l) => l.scope.length > 0);

    const byPrefix = new Map<string, Law[]>();
    for (const law of scoped) {
      const pref = commonPrefix(law.scope) || "_misc";
      const list = byPrefix.get(pref) ?? [];
      list.push(law);
      byPrefix.set(pref, list);
    }

    const artifacts: CompiledArtifact[] = [];
    const rootParts: string[] = [
      "## speclaw laws (generated)",
      "",
      "_Edit `docs/standards/*.md` or `.speclaw/laws-manifest.json`; do not edit this block._",
      "",
    ];
    rootParts.push(...workflowSection(ctx.projectPath));
    if (global.length) rootParts.push(degradeSection("Global rules", global));

    const nestedMention: string[] = [];
    for (const [pref, group] of [...byPrefix.entries()].sort(([a], [b]) => a.localeCompare(b))) {
      const pkg = pref !== "_misc" && pref.length > 0;
      const nest =
        pkg &&
        group.length >= NESTED_THRESHOLD &&
        // Nested only when a package.json exists under that prefix.
        true;
      // Nesting is decided by the orchestrator (fs check); here we always
      // put dense prefixes in a nested artifact path hint via mode write.
      if (nest && pref !== "_misc") {
        nestedMention.push(pref);
        artifacts.push({
          path: `${pref}/AGENTS.md`,
          contents: delimit(
            "laws",
            degradeSection(`Rules for \`${pref}\``, group) +
              `\n_Generated by speclaw from law ids: ${group.map((l) => l.id).join(", ")}_\n`,
          ),
          lawIds: group.map((l) => l.id),
          mode: "write",
        });
      } else {
        const title = pref === "_misc" ? "Scoped rules" : `Rules for \`${pref}\``;
        rootParts.push(degradeSection(title, group));
      }
    }
    if (nestedMention.length) {
      rootParts.push("## Nested AGENTS.md files", "");
      for (const p of nestedMention) rootParts.push(`- [\`${p}/AGENTS.md\`](${p}/AGENTS.md)`);
      rootParts.push("");
    }

    void ctx;
    artifacts.push({
      path: "AGENTS.md",
      contents: rootParts.join("\n"),
      lawIds: active.map((l) => l.id),
      mode: "patch-delimited",
      marker: "laws",
    });

    artifacts.push({
      path: "CLAUDE.md",
      contents: [
        "## speclaw (generated)",
        "",
        "Import shared agent context: `@AGENTS.md`",
        "",
        "Path-scoped laws live under `.claude/rules/` (symlink to `ai-specs/rules`).",
        "Do not rely on Claude Code reading `AGENTS.md` without the import.",
        "",
      ].join("\n"),
      lawIds: active.map((l) => l.id),
      mode: "patch-delimited",
      marker: "laws",
    });

    return artifacts;
  },
};
