import fs from "node:fs";
import path from "node:path";
import { InstallReport, ensureGitignore } from "./install.js";
import { pkgName, pkgVersion } from "./version.js";

/** Describes an AI coding agent speclaw knows how to wire into a project. */
export interface AgentDef {
  /** Stable identifier used on the CLI and in reports. */
  id: string;
  /** Human-readable name for display. */
  label: string;
  /** IDE directory that mirrors ai-specs via symlinks. */
  ideDir: string;
  /** ai-specs subdirectories this agent reads. */
  linkTargets: string[];
  /** Where this agent looks for its MCP server config (relative to project). Omit if it has no MCP. */
  mcpFile?: string;
  /**
   * Where this agent's hooks live and the JSON key they sit under. Omit if the
   * agent has no hook support — the hook compiler then skips it by construction
   * (not by an `id === "claude"` branch), and `doctor` reports the asymmetry.
   */
  hooks?: { file: string; key: string };
}

/** The agents speclaw can configure. Add one here and the CLI picks it up. */
export const AGENTS: AgentDef[] = [
  {
    id: "claude",
    label: "Claude Code",
    ideDir: ".claude",
    linkTargets: ["skills", "commands", "agents"],
    mcpFile: ".mcp.json",
    hooks: { file: ".claude/settings.json", key: "hooks" },
  },
  {
    id: "cursor",
    label: "Cursor",
    ideDir: ".cursor",
    linkTargets: ["skills", "commands", "rules", "agents"],
    mcpFile: ".cursor/mcp.json",
  },
  {
    id: "codex",
    label: "Codex",
    ideDir: ".codex",
    linkTargets: ["skills", "commands", "agents"],
    mcpFile: ".codex/mcp.json",
  },
  {
    id: "windsurf",
    label: "Windsurf",
    ideDir: ".windsurf",
    linkTargets: ["skills", "commands", "agents"],
    mcpFile: ".windsurf/mcp.json",
  },
  {
    id: "agents",
    label: "Generic (AGENTS.md)",
    ideDir: ".agents",
    linkTargets: ["skills", "agents"],
  },
];

/**
 * Look up a known agent definition by its id.
 *
 * @param id - The agent identifier (e.g. `"claude"`, `"cursor"`).
 * @returns The matching {@link AgentDef}, or `undefined` if no agent has that id.
 */
export function agentById(id: string): AgentDef | undefined {
  return AGENTS.find((a) => a.id === id);
}

/** The shape of the `speclaw` server entry in an agent's MCP config. */
export interface McpEntry {
  type: string;
  command: string;
  args: string[];
}

/**
 * The speclaw MCP server entry, pinned to the running package version so the
 * agent's MCP server matches the CLI that wrote the config (an unpinned entry
 * runs whatever npx happens to have cached).
 *
 * @returns `npx -y <pkg>@<version> mcp` over stdio.
 */
// Covers: req~mcp-entry-pinned~1
export function mcpEntry(): McpEntry {
  return { type: "stdio", command: "npx", args: ["-y", `${pkgName()}@${pkgVersion()}`, "mcp"] };
}

/**
 * Whether an existing `speclaw` entry is the stock npx launcher speclaw wrote
 * (pinned or not), as opposed to a custom one the user owns.
 *
 * @param entry - The existing `mcpServers.speclaw` value.
 * @returns True for `{ type?, command: "npx", args: ["-y", <pkg>[@<v>], "mcp"] }`.
 */
function isStockMcpEntry(entry: unknown): boolean {
  if (!entry || typeof entry !== "object" || Array.isArray(entry)) return false;
  const e = entry as Record<string, unknown>;
  if (Object.keys(e).some((k) => k !== "type" && k !== "command" && k !== "args")) return false;
  if (e.command !== "npx" || !Array.isArray(e.args) || e.args.length !== 3) return false;
  const [y, pkg, mcp] = e.args as unknown[];
  const name = pkgName();
  return (
    y === "-y" &&
    mcp === "mcp" &&
    typeof pkg === "string" &&
    (pkg === name || pkg.startsWith(`${name}@`))
  );
}

/** True when `p` exists as a filesystem entry (including a symlink), without following it. */
function isSymlink(p: string): boolean {
  try {
    fs.lstatSync(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * Register the speclaw stdio MCP server in an agent's config file, merging into
 * any existing config. A missing entry is written pinned; a stock npx entry
 * (pinned to another version or unpinned) is re-pinned; any other shape is a
 * custom entry and is kept untouched.
 */
function writeMcpConfig(projectPath: string, mcpFile: string, report: InstallReport): void {
  // The agent MCP config is per-developer wiring — regenerated by `speclaw init`
  // / `agent add`, points at a local runner — not shared source. Keep it out of
  // version control (done regardless of whether we write or skip the file below).
  ensureGitignore(
    projectPath,
    mcpFile,
    "speclaw agent MCP config (per-developer; regenerated by init)",
    report,
  );

  const mcpPath = path.join(projectPath, mcpFile);
  let config: { mcpServers?: Record<string, unknown> } = {};
  if (fs.existsSync(mcpPath)) config = JSON.parse(fs.readFileSync(mcpPath, "utf8"));
  config.mcpServers = config.mcpServers ?? {};
  const pinned = mcpEntry();
  const existing = config.mcpServers["speclaw"];
  let note = "speclaw MCP server";
  if (existing) {
    if (!isStockMcpEntry(existing)) {
      report.skipped.push(`${mcpPath} (custom speclaw entry kept)`);
      return;
    }
    const e = existing as Partial<McpEntry>;
    if (e.type === pinned.type && JSON.stringify(e.args) === JSON.stringify(pinned.args)) {
      report.skipped.push(`${mcpPath} (speclaw already registered)`);
      return;
    }
    note = `speclaw MCP entry pinned to ${pkgVersion()}`;
  }
  config.mcpServers["speclaw"] = pinned;
  fs.mkdirSync(path.dirname(mcpPath), { recursive: true });
  fs.writeFileSync(mcpPath, JSON.stringify(config, null, 2) + "\n");
  report.written.push(`${mcpPath} (${note})`);
}

/**
 * Configure one agent: create its symlinks into ai-specs and register the MCP server.
 *
 * @param projectPath - Project root to configure.
 * @param agentId - Id of a known agent (see {@link AGENTS}).
 * @param report - Report mutated in place with created symlinks and written/skipped paths.
 * @throws Error if `agentId` does not match any known agent.
 */
export function configureAgent(projectPath: string, agentId: string, report: InstallReport): void {
  const agent = agentById(agentId);
  if (!agent)
    throw new Error(`Unknown agent "${agentId}". Known: ${AGENTS.map((a) => a.id).join(", ")}`);

  const ideRoot = path.join(projectPath, agent.ideDir);
  for (const target of agent.linkTargets) {
    const sourceDir = path.join(projectPath, "ai-specs", target);
    if (!fs.existsSync(sourceDir)) continue;
    fs.mkdirSync(ideRoot, { recursive: true });
    const linkPath = path.join(ideRoot, target);
    if (fs.existsSync(linkPath) || isSymlink(linkPath)) {
      report.skipped.push(linkPath);
      continue;
    }
    fs.symlinkSync(path.join("..", "ai-specs", target), linkPath);
    report.symlinks.push(`${linkPath} -> ../ai-specs/${target}`);
  }

  if (agent.mcpFile) writeMcpConfig(projectPath, agent.mcpFile, report);
}

/**
 * List the agents already set up in this project (their IDE dir exists).
 *
 * @param projectPath - Project root to inspect.
 * @returns The ids of agents whose IDE directory is present.
 */
export function detectConfiguredAgents(projectPath: string): string[] {
  return AGENTS.filter((a) => fs.existsSync(path.join(projectPath, a.ideDir))).map((a) => a.id);
}

/**
 * Re-run configuration for every already-configured agent (e.g. after adding a pack).
 *
 * @param projectPath - Project root whose configured agents should be refreshed.
 * @param report - Report mutated in place across all refreshed agents.
 */
export function refreshAgents(projectPath: string, report: InstallReport): void {
  for (const id of detectConfiguredAgents(projectPath)) configureAgent(projectPath, id, report);
}
